name: links

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - uses: actions/checkout@v4
        with:
          repository: glossarist/migration-adapters

      - name: Enable Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      # - name: Compile all packages
      #   # TODO: Get rid of, the esbuild step should be sufficient.
      #   # However, currently some packages rely on `compiled/` paths,
      #   # which are created by running `compile` commands.
      #   run: |
      #     yarn compile-all

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build site
        run: |
          yarn workspace webgui build --debug

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --verbose --no-progress --exclude-file .lycheeignore -- _site/**/*.html
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v2
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
